const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#4A9EE0",
    background: "#F2F6FB",
    foreground: "#0F1A2A",
    card: "#FFFFFF",
    cardForeground: "#0F1A2A",
    primary: "#4A9EE0",
    primaryForeground: "#FFFFFF",
    secondary: "#E8F0FA",
    secondaryForeground: "#0F1A2A",
    muted: "#E8F0FA",
    mutedForeground: "#7A8CA0",
    accent: "#2176C7",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#D0DAEA",
    input: "#D0DAEA",
    success: "#22C55E",
    warning: "#F59E0B",
  },
  dark: {
    text: "#F2F6FB",
    tint: "#4A9EE0",
    background: "#0A1420",
    foreground: "#F2F6FB",
    card: "#0F1D2E",
    cardForeground: "#F2F6FB",
    primary: "#4A9EE0",
    primaryForeground: "#FFFFFF",
    secondary: "#162236",
    secondaryForeground: "#F2F6FB",
    muted: "#162236",
    mutedForeground: "#7A8CA0",
    accent: "#5BB0F0",
    accentForeground: "#0F1A2A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3048",
    input: "#1E3048",
    success: "#22C55E",
    warning: "#F59E0B",
  },
  radius: 12,
};

export default colors;
